# ./docker-compose.yml

version: "3.9"

services:
  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    volumes:
      - mongo-data:/data/db

  backend:
    build: .
    ports:
      - "${PORT}:${PORT}" # Use the environment variable for the port mapping
    env_file:
      - .env
    volumes:
      - .:/backend
    depends_on:
      - mongodb
    command: npm run dev

volumes:
  mongo-data:
