// src/config/config.ts
export const GENERATIVE_MODELS = [
    { value: 'GPT_3_5_TURBO', label: 'GPT-3.5 Turbo' },
    { value: 'GPT_4', label: 'GPT-4' },
];
export const MUSIC_INSTRUMENTS = [
    "AcousticGrandPiano",
    "ElectricGrandPiano",
    "ElectricPiano1",
    "AcousticGuitarNylon",
    "ElectricGuitarClean",
    "OverdrivenGuitar",
    "AcousticBass",
    "ElectricBassFinger",
    "Violin",
    "Cello",
    "OrchestralHarp",
    "StringEnsemble1",
    "SynthStrings1",
    "ChoirAahs",
    "Trumpet",
    "Trombone",
    "FrenchHorn",
    "AltoSax",
    "TenorSax",
    "Flute",
    "PanFlute",
    "Lead1Square",
    "Lead2Sawtooth",
    "TinkleBell",
    "SteelDrums",
];
